name: janvaani
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  camera: ^0.10.5+9
  dio: ^5.4.1
  flutter_secure_storage: ^9.0.0
  http: ^1.2.1
  http_parser: ^4.0.2
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  lottie: ^3.1.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  path_provider: ^2.1.2
  saver_gallery: ^4.0.1
  image: ^4.2.0
  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/loading.json
    - assets/

# ✅ App Icon Configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
